tasks:
  - name:    Add several users
    user:
      name:   "{{ item }}"  ## loopの値が1つずつ展開される
      state:  present
      groups: "wheel"
    loop:
      - user01
      - user02
      - user03

  ## マッピングを利用したloop処理
  - name: Add several users2
    user:
      name:   "{{ item.name }}"
      state:  present
      groups: "{{ item.groups }}"
    loop:
      - { name: "user01", groups: "wheel" }
      - { name: "user02", groups: "admin" }
